name: comparators
description: A package providing simple Java-like comparators in Dart.
version: 0.0.1
repository: https://github.com/mitryp/comparators

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
